### ISSUE TITLE
Where is to find your GPG key?

### ISSUE THREAD

**Issue by vt-alt** [ptesarik/libkdumpfile#68]
It seems you signing your git tags., But where to get your key?

1. Key at https://github.com/ptesarik.gpg have `no valid user IDs`.
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Note: The keys with the following IDs couldn't be exported and need to be reuploaded AA503BC9AE0F47A7

mDMEY6RYZBYJKwYBBAHaRw8BAQdAxf1EDxamzQVXNJt1FyXn45j18vPFKBDEFP6X
1IsbEJC0H1BldHIgVGVzYXJpayA8cGV0ckB0ZXNhcmljaS5jej6ImQQTFgoAQRYh
BBHfqaditAM1cWefz896blmSvJlKBQJjpFhkAhsDBQkCeNAABQsJCAcCAiICBhUK
CQgLAgQWAgMBAh4HAheAAAoJEM96blmSvJlKv/AA/ibHEYnfsItcdlvzGIXuSEju
Ic9Te8LzD13LqXZ91vA4AQCAzc4A9Q++DBBaCscGiDuCnmattCseb0OBjWXOFjKp
AokBNgQQAQgAIBYhBB5dmCGZCKOVTtjMWKpQO8muD0enBQJjpFlaAgcAAAoJEKpQ
O8muD0enrccIAJY/+TXRdNg+e2jH+AzSL/GHbjeThInD+giQEUfXbLC32+pcP85A
yy3zXcWplJO0n3LdpJynZwdYo9AbZ2yn8J+QUG9tTmeJ3KvNc8b3DW6NnAMVz2cG
TpbFTUou6n2IyRcpOTNJvV0SqEFH9x1N9lEiP8QQAUEjWuo5gfIZ4qc6t1Wm16Wm
bbslOgExbqjErU89I885JM/4N34YGffcNcNHD/rxEHP9VWfQ6yNsWzf0kbPKJ6i/
brZbxHdNfCj6sXIJ09GmC8CjM0KLKSl12Opudsj1m/HHf1WfuWsV8t3eFqZ3QMBD
GVFWYmjd2/ltb4HTAxW55blFMGlSOWSAWqG4OARjpFhkEgorBgEEAZdVAQUBAQdA
6MJIcbxdqiK6aW+eT4mr2bxYDmKjHMLpsMzxDZO9ij8DAQgHiH4EGBYKACYWIQQR
36mnYrQDNXFnn8/Pem5ZkryZSgUCY6RYZAIbDAUJAnjQAAAKCRDPem5ZkryZSgLm
AP4jS5ZhSj+BQ7dJM/j5rrHE72sBsrlytzOA0/v3GNFG8wD8DZIeYsl8DF4A/o+d
isPB1rJqsLo3b375xeqCgRZvAQU=
=yHkj
-----END PGP PUBLIC KEY BLOCK-----
```
2. Key at https://keys.openpgp.org/search?q=petr%40tesarici.cz not found.

Thanks,

**Comment by ptesarik** [comment]
Good question!

I used to sign all my commits with GPG key AA503BC9AE0F47A7, but I created a new GPG key after leaving SUSE at the end of last year and I'm now signing my commits with key CF7A6E5992BC994A. I have also uploaded the new key to GitHub. That's why GitHub marks them as verified.

Now the possible caveats:
- My old key was a rsa4096 key, my current key is an ed25519 key, which is not yet handled by all tools, it seems.
- The old key was for ptesarik@suse.com and ptesarik@suse.de, but I'm now using my private email (petr@tesarici.cz).
- I also tried to add my private email to the old key, but I did not find any way to update an existing GPG key at GitHub.
- I did not upload my new key to keys.openpgp.org, but it is available from the Ubuntu server:
  https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x11dfa9a762b4033571679fcfcf7a6e5992bc994a

I'm going to upload my new key to openpgp.org at least…

**Comment by ptesarik** [comment]
I have also deleted the old key from GitHub, which fixed the GPG export at https://github.com/ptesarik.gpg, but it has also made my older commits under ptesarik@suse.com appear as Unverified. Hm.

Anyway, I believe this issue can be closed.

**Comment by vt-alt** [comment]
Thanks much!
